### ISSUE TITLE
there are some annotations do not match the dataset

### ISSUE THREAD

**Issue by HangFang6** [xujinglin/FineDiving#1]
For example, ('14', 55) has a total of 98 images, but the annotation file only shows the annotations of 94 images.
![image](https://user-images.githubusercontent.com/87681879/167254179-b4781fac-882f-4302-ada3-424d849cc29f.png)
![image](https://user-images.githubusercontent.com/87681879/167254205-c0acaf0c-f27d-42ca-b3c8-7fe82ae03834.png)

**Comment by HangFang6** [comment]
My solution is based on annotation and removes redundant images from back to front. I hope the author can give a better suggestions.

**Comment by xujinglin** [comment]
> My solution is based on annotation and removes redundant images from back to front. I hope the author can give a better suggestions.

Thanks for your attention~~~
Actually, we fixed a few annotation files and re-uploaded their image files last month. Please download the newest version.
If it still doesn't work, please let me know.

**Comment by HangFang6** [comment]
Excellent job！
That's work. Thanks for your reply！
