### ISSUE TITLE
Full dataset in Baidu Netdisk is broken

### ISSUE THREAD

**Issue by ghost** [xujinglin/FineDiving#2]
The full dataset in Baidu Netdisk is broken. Could you please upload a new version?
OR may be the broken is about the Video_Frames (Not sure)? 
How about compress them to a zip file?
Thanks!

![image](https://user-images.githubusercontent.com/59056753/173006661-f11d114a-3fa6-431e-8d14-6673ed80ca9b.png)

**Comment by xujinglin** [comment]
I have checked and updated.
If it doesn't work, try downloading it from Google Drive.
