### ISSUE TITLE
how is the ground truth score computed from the judge scores

### ISSUE THREAD

**Issue by Picasso-Wang** [xujinglin/FineDiving#3]
Hi, I am wondering how the ground truth score is computed from the judge scores.
For example, in the datapoint 'FineDiving/FINDADiving_MTL_2546s/01/74'，the judge scores are [5.0, 6.0, 5.5, 4.5, 4.5, 5.5, 6.0]，while the ground truth score is 57.6. How is this ground truth score computed?
Thank you very much.

**Comment by xujinglin** [comment]
Hi, thanks for your interest in our work.

Actually, we utilize the final score as the ground truth score rather than the judge scores.

**Comment by Picasso-Wang** [comment]
Got it. Thank you.
