### ISSUE TITLE
Baidu cloud data is missing and cannot be downloaded.

### ISSUE THREAD

**Issue by YuyanXu0329** [xujinglin/FineDiving#4]
When the dataset is saved, Baidu Cloud pops up that the xxx file is missing and the save fails. Could you please give me a complete dataset, thanks

**Comment by xujinglin** [comment]
Hi, thanks for your interest in our work.

I have checked the Baidu Cloud and it works well. Please try it again.
Please let me know if it still does not work.

**Comment by YuyanXu0329** [comment]
Hi, when I save to my Baidu Cloud, he will pop up this question, thank you.







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jinglin ***@***.***&gt;; 
发送时间: 2022年8月4日(星期四) 下午3:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xujinglin/FineDiving] Baidu cloud data is missing and cannot be downloaded. (Issue #4)





 
Hi, thanks for your interest in our work.
 
I have checked the Baidu Cloud and it works well. Please try it again.
 Please let me know if it still does not work.
